version: '2'
services:
  couch:
    container_name: couch.orderer.example.com
    image: hyperledger/fabric-couchdb:x86_64-1.1.0-preview
    # Populate the COUCHDB_USER and COUCHDB_PASSWORD to set an admin user and password
    # for CouchDB.  This will prevent CouchDB from operating in an "Admin Party" mode.
    environment:
      - COUCHDB_USER=
      - COUCHDB_PASSWORD=
#    ports:
#      - 5984:5984 # TODO: allow for multiple
